RequestApplication.WebUI/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RequestApplication.BLL.Abstract;
using RequestApplication.Entitiy;
using RequestApplication.WebUI.Models;

namespace RequestApplication.WebUI.Controllers
{
    [Authorize(Roles = "User")]
    public class RequestController : Controller
    {
        private readonly IRequestBLL _requestBLL;
        private readonly IMapper _mapper;
        public RequestController(IRequestBLL requestBLL, IMapper mapper)
        {
            _requestBLL = requestBLL;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RequestCreateViewModel model, IFormFile document)
        {
            if (!ModelState.IsValid)
            {

                return View(model);
            }

            else
            {
                if (document != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\document", document.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await document.CopyToAsync(stream);

                        model.Document = document.FileName;
                    }
                }
                else
                {
                    ModelState.AddModelError("FileError", "Dosya alanı zorunludur");
                    return View();
                }

                var userId = User.Claims.Where(a => a.Type == ClaimTypes.NameIdentifier).Select(a => a.Value).FirstOrDefault();

                model.UserId = Convert.ToInt32(userId);
    
                var request = _mapper.Map<Request>(model);

                _requestBLL.AddRequest(request);

                return RedirectToAction("List");
            }
        }
        public IActionResult Details(int id)
        {

            var userId = User.Claims.Where(a => a.Type == ClaimTypes.NameIdentifier).Select(a => a.Value).FirstOrDefault();

            if (_requestBLL.GetRequest(id).UserId == Convert.ToInt32(userId))
            {
                var request = _requestBLL.GetRequest(id);

                var model = _mapper.Map<RequestDetailsViewModel>(request);

                return View(model);
            }

            return RedirectToAction("AccessDenied", "Account");
            
        }
        public IActionResult List()
        {
            var userEmail = User.Claims.Where(a => a.Type == ClaimTypes.Email).Select(a => a.Value).FirstOrDefault();

            var requests = _requestBLL.GetAllRequests().Where(a => a.User.Email == userEmail).ToList();

            var model = _mapper.Map<List<RequestListViewModel>>(requests);

            return View(model);
        }


    }
}

RequestApplication.WebUI/Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RequestApplication.BLL.Abstract;
using RequestApplication.Entitiy;
using RequestApplication.WebUI.Models;
using static System.Net.Mime.MediaTypeNames;

namespace RequestApplication.WebUI.Controllers
{

    [Authorize(Roles = "Admin")]
    public class ResponseController : Controller
    {
        private readonly IRequestBLL _requestBLL;
        private readonly IMapper _mapper;
        private readonly IMailBLL _mailBLL;
        private readonly IDocumentBLL _documentBLL;

        public ResponseController(IRequestBLL requestBLL, IMapper mapper, IMailBLL mailBLL, IDocumentBLL documentBLL)
        {
            _requestBLL = requestBLL;
            _mapper = mapper;
            _mailBLL = mailBLL;
            _documentBLL = documentBLL;
        }

        public IActionResult List()
        {
            var responses = _requestBLL.GetAllRequests().OrderByDescending(a => a.RequestDate).ToList();

            var model = _mapper.Map<List<ResponseListViewModel>>(responses);

            return View(model);
        }
        [HttpGet]

        public IActionResult Answer(int id)
        {
            var response = _requestBLL.GetRequest(id);

            var model = _mapper.Map<ResponseAnswerViewModel>(response);

            return View(model);
        }
        [HttpPost]

        public IActionResult Answer(ResponseAnswerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Cookie'de olan user'ın Id'sini alıyoruz

            var adminId = User.Claims.Where(a => a.Type == ClaimTypes.NameIdentifier).Select(a => a.Value).FirstOrDefault();

            model.AdminId = Convert.ToInt32(adminId);

            var request = _mapper.Map<Request>(model);

            _requestBLL.UpdateRequest(request);

            _mailBLL.SendMail(request);

            return RedirectToAction("List");
        }

        public IActionResult Download(string id)
        {
            var document = _documentBLL.Download(id);

            return File(document, "application/force-download", id);
        }

        public IActionResult Report(int id)
        {
            var report = _documentBLL.Report(id);

            return File(report, "application/force-download", "report.txt");
        }


    }
}

RequestApplication.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-paper-plane fa-lg"></i>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">

                    @if (User.IsInRole("User"))
                    {
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Request" asp-action="List">Talep Ekle</a>
                            </li>
                        </ul>
                    }

                    else if (User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Response" asp-action="List">Talep Yanıtla</a>
                            </li>
                        </ul>
                    }




                <ul class="navbar-nav ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout">
                                <i class="fas fa-sign-out-alt fa-lg"></i>
                            </a>
                        </li>
                    }

                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">
                                <i class="fas fa-sign-in-alt fa-lg"></i>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">
                                <i class="fas fa-user-plus fa-lg"></i>
                            </a>
                        </li>

                    }
                </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white text-center bg-dark">
        <div class="container">
            &copy; 2020 - Bu site Tabim Bilişim için hazırlanmıştır.
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/612e8753d8.js" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>